version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: aprendecoding-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_root
      MONGO_INITDB_ROOT_PASSWORD: admin_root
    volumes:
      - mongo_data:/data/db

  devserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aprendecodingapi
    ports:
      - "3002:3002"
    env_file: env/dev.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongodb
    profiles:
      - dev

volumes:
  mongo_data:
