version: '3.8'

services:

  devserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aprendecodingapi
    ports:
      - "3002:3002"
    env_file: env/dev.env
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

