export class SessionCompletedDto {
  id: string;
  object: string;
  after_expiration: null;
  allow_promotion_codes: boolean;
  amount_subtotal: number;
  amount_total: number;
  automatic_tax: { enabled: boolean; status: null };
  billing_address_collection: string;
  cancel_url: string;
  client_reference_id: null;
  consent: null;
  consent_collection: { promotions: string; terms_of_service: string };
  created: number;
  currency: string;
  currency_conversion: null;
  custom_fields: any[];
  custom_text: { shipping_address: null; submit: null };
  customer: null;
  customer_creation: string;
  customer_details: {
    address: object;
    email: string;
    name: string;
    phone: null;
    tax_exempt: string;
    tax_ids: any[];
  };
  customer_email: null;
  expires_at: number;
  invoice: null;
  invoice_creation: { enabled: boolean; invoice_data: object };
  livemode: boolean;
  locale: string;
  metadata: object;
  mode: string;
  payment_intent: string;
  payment_link: string;
  payment_method_collection: string;
  payment_method_options: { card: object };
  payment_method_types: string[];
  payment_status: string;
  phone_number_collection: { enabled: boolean };
  recovered_from: null;
  setup_intent: null;
  shipping_address_collection: null;
  shipping_cost: null;
  shipping_details: null;
  shipping_options: any[];
  status: string;
  submit_type: string;
  subscription: null;
  success_url: string;
  total_details: {
    amount_discount: number;
    amount_shipping: number;
    amount_tax: number;
  };
  url: null;
}
